### ISSUE TITLE
/feed can't feed others

### ISSUE THREAD

**Issue by XDqrkneZ** [Shelly7w7/ShellyEssentials-#1]
/feed can't feed others

**Comment by Shelly7w7** [comment]
Thanks for the issue will be added soon!

**Comment by iiFlamiinBlaze** [comment]
https://github.com/Shelly7w7/ShellyHealFeed

**Comment by iiFlamiinBlaze** [comment]
Fixed with commit e89bd281a6beab25728d105af1914524ccc35586
