### ISSUE TITLE
Join Title duplicates to Subtitle

### ISSUE THREAD

**Issue by xXRyzen** [Shelly7w7/ShellyEssentials-#14]
Join title "Test" is also put in subtitle spot ignoring below example of "Hello".

---------------------------------------------------------------------------------------------
The below config is the title that will show when the player joins the server.
To show the player's name use {playername}.
join-title: "Test"

The below config is the subtitle that will show when the player joins the server
To show the player's name use {playername}.
join-subtitle: "Hello"

--------------------------------------------------------------------------------------------
![join](https://user-images.githubusercontent.com/15342124/55859230-7e751d00-5b26-11e9-89f0-41cbe40e7bc1.jpg)

**Comment by Shelly7w7** [comment]
It's a minecraft bug, however I'll find a hack.

**Comment by xXRyzen** [comment]
Thank you!

**Comment by AlexPads** [comment]
@Shelly7w7 its not a bug look at your code again -_- you have the Same variables for each.

**Comment by Shelly7w7** [comment]
> @Shelly7w7 its not a bug look at your code again -_- you have the Same variables for each.

Gotcha, ty for informing
