### ISSUE TITLE
how to enable tpa/tpaccept/tpdeny

### ISSUE THREAD

**Issue by trine342** [Shelly7w7/ShellyEssentials-#5]
how to enable tpa/tpaccept/tpdeny and can u add warp command bcs ur plugin make warp plugin error

**Comment by trine342** [comment]
and how to set message from ur clear lagg and how i set the interval?

**Comment by trine342** [comment]
and when i use world tp i disconected and it say internal server error

**Comment by piyushbest** [comment]
to/tpaccept/tpdeny is not added and clear lag u can edit code of msg

**Comment by Shelly7w7** [comment]
Hello, this feature is in todo list. It will be released soon.
